### PR TITLE
feat: allow pact-message update to receive JSON via the standard input

### PR DESCRIPTION
**Pull request by aussiDavid**
Fix issue [#61](https://github.com/pact-foundation/pact-ruby-standalone/issues/61) on [pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone)

@TimothyJones made me do this. I obliged :).

### CODE REVIEW

**Comment by TimothyJones** [comment]
Hahaha! For context for others:

David: "What should I put in the PR description?"
Me: "Doesn't really matter, tell them I made you do if you like"

Thanks David! You're awesome!

@bethesque - how do we go about getting this in to the standalone? It will fix the issues with pact-js' windows build.

**Comment by bethesque** [comment]
Tim makes me do a lot of things too.

@aussiDavid can you add a spec to this file please https://github.com/pact-foundation/pact-message-ruby/blob/master/spec/features/cli_spec.rb

**Comment by bethesque** [comment]
@TimothyJones once this is released, it will automatically trigger an update and release of the ruby standalone, via the magic of Github Actions.

**Comment by aussiDavid** [comment]
The test has been added.

**Comment by bethesque** [comment]
Thank you :)

**Comment by bethesque** [comment]
@TimothyJones note the dispatch action to trigger the release of the pact-cli and the pact-ruby-standalone

https://github.com/pact-foundation/pact-message-ruby/runs/1759000952?check_suite_focus=true

This is one of the reasons that using a dispatch action to trigger a release rather than doing it on a tag is handy.

**Comment by TimothyJones** [comment]
Yeah! I’m not sure I told you, but I read through the links you sent and was really impressed. Pact JS now releases from a dispatch action- and when I do pact-node and jest-pact I’ll probably do a docker release action like did for ruby.

(Also I shamelessly borrowed your trigger-release script).

Is the pact-node auto PR script still disabled? I haven’t seen the PR, but also haven’t looked into it yet.

**Comment by bethesque** [comment]
I was running the script from my local machine when I did a release, but because I never release locally any more, it hasn't been run for a while. What I can do is add a notification to pact-node when the standalone releases with the same deets as the above notification, and you could turn the PR script into a workflow.

**Comment by bethesque** [comment]
Oh, in the trigger-release script, I've had to update 

```
if  ! echo "${output}" | grep "HTTP\/.* 204" > /dev/null; then
```

to 

```
```

**Comment by bethesque** [comment]
BAM. Got you a dispatch action for pact-node

https://github.com/pact-foundation/pact-ruby-standalone/runs/1759562313?check_suite_focus=true#step:2:7

**Pull request merged**
